S=str(input('Introduceti sirul:'))
x=S.upper()
a=x.count('A')
b=x.replace('A','*')
c=x.replace('B','')
d=x.count('MA')
e=x.replace('MA','TA')
f=x.replace('TO','')
print('a)numarul de aparitii ale caracterului A in sirul x:',a)
print('b)şirul obţinut prin substituirea caracterului ’A’ prin caracterul ’*’:',b)
print('c)şirul obţinut prin radierea din şirul x a tuturor apariţiilor caracterului ’B’:',c)
print('d)numărul de apariţii ale silabei MA în şirul x:',d)
print('e)şirul obţinut prin substituirea tuturor apariţiilor în şirul S a silabei MA prin silaba TA:',e)
print('f)şirul obţinut prin radierea din şirul S a tuturor apariţiilor silabei TO:',f)
print('g)scrierea inversă a şirului x:',x[::-1])